# Generated by Django 3.2 on 2021-04-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0002_foodtable_ftag'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtable',
            name='fUrl',
            field=models.CharField(default='', max_length=255),
        ),
    ]
