# Generated by Django 3.2 on 2021-04-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0005_auto_20210430_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtable',
            name='fFoodImage',
        ),
        migrations.RemoveField(
            model_name='foodtable',
            name='fMenuImage',
        ),
    ]
