# Generated by Django 2.2.5 on 2021-05-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0008_foodtable_fmenuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtable',
            name='fMenuImage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/menu/'),
        ),
    ]
