# Generated by Django 2.2.5 on 2021-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0011_auto_20210502_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtable',
            name='fMenuImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/menu/'),
        ),
    ]
