# Generated by Django 3.1.4 on 2021-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0015_auto_20210521_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbikeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snoe', models.CharField(max_length=10)),
                ('sna', models.CharField(max_length=20)),
                ('sbi', models.CharField(max_length=20)),
                ('bemp', models.CharField(max_length=20)),
            ],
        ),
    ]
