# Generated by Django 3.1.4 on 2021-05-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0016_ubikedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubikedata',
            old_name='snoe',
            new_name='sno',
        ),
    ]
