# Generated by Django 3.2 on 2021-04-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0003_foodtable_furl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtable',
            name='fPhone',
        ),
    ]
