# Generated by Django 2.2.5 on 2021-05-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0006_auto_20210430_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
