# Generated by Django 2.2.5 on 2021-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyimapp', '0009_auto_20210502_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtable',
            name='fMenuImage',
            field=models.ImageField(blank=True, null=True, upload_to='image/menu/'),
        ),
    ]
